### ISSUE TITLE
权限不足.  DNS Redir: operation not permitted

### ISSUE THREAD

**Issue by senocids** [Kr328/clash-premium-installer#8]
看了几个文档, 发现这个 repo 是集官方文档以及官方文档的引用的大成者.   感谢
不过, 有一些问题.

### 一些勘误? 
不明白文件夹 `/srv/clash/` 是 644

```diff
installer.sh:
44:-  assert install -d -m 0644 /srv/clash/
44:+  assert install -d -m 0744 /srv/clash/
88:-  rm -rf /usr/bin/bypass-proxy-uid
88:+  rm -rf /usr/bin/bypass-proxy-pid
```

### 环境
<details>
  <summary>raspbian buster</summary>

```bash
$ uname -a
Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux
$ ./clash -v
Clash 2021.03.10 linux arm64 Wed Mar 10 13:32:16 UTC 2021
```
</details>

#### 问题
- 使用默认用户 pi, 无法开启 URP redirect 
- 使用 sudo 解决问题
- 如下 log, 已将 DNS 端口改成 > 1024. 依旧需要权限
- TProxy server 也有同样的问题, 但不是此 issue 重点

<details>
  <summary>config.yaml</summary>
  
```yaml
# Port of HTTP(S) proxy server on the local end
# port: 7890

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
tproxy-port: 7893

# HTTP(S) and SOCKS5 server on the same port
mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: true

# RESTful web API listening address
external-controller: 0.0.0.0:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
external-ui: yacd-gh-pages

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
secret: ""

# Outbound interface name
interface-name: eth0

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: true
  listen: 0.0.0.0:50053
  ipv6: true # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: redir-host # or fake-ip
  # fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record
  
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
  
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 119.29.29.29
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS

  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  fallback:
    - tcp://1.1.1.1
    
  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
  # are always used if not match `fallback-filter.ipcidr`.
  #
  # This is a countermeasure against DNS pollution attacks.
  fallback-filter:
    geoip: true
    # ips in these subnets will be considered polluted
    ipcidr:
      - 240.0.0.0/4
    # domain:
    #   - '+.google.com'
    #   - '+.facebook.com'
    #   - '+.youtube.com'
tun:
  enable: true
  stack: gvisor # or system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53
    - 8.8.8.8:1053
...
...
```
</details>

<details>
  <summary>根据 config 修改 clash-default 中 dns 端口</summary>
  
```diff
diff --git a/scripts/clash-default b/scripts/clash-default
@@ -9,7 +9,7 @@ NETFILTER_MARK=114514
 # iproute2 rule table id
 IPROUTE2_TABLE_ID=114
 
-# dns redirect
-FORWARD_DNS_REDIRECT=1.0.0.1:53
+# dns redirect, match dns listen in clash config
+FORWARD_DNS_REDIRECT=0.0.0.1:50053
```
</details>

<details>
  <summary>更改 daemon 使用默认用户组. 此项不重要, 不用 daemon 也有相同问题</summary>

```diff
diff --git a/scripts/clash.service b/scripts/clash.service
@@ -4,8 +4,14 @@ After=network-online.target nftables.service iptabels.service
 
 [Service]
 Type=simple
-ExecStartPre=+/usr/lib/clash/setup-cgroup.sh
-ExecStart=/usr/bin/bypass-proxy /usr/bin/clash -d /srv/clash
+StandardError=journal
+User=pi
+Group=pi
+ExecStartPre=+/home/pi/lib/clash/setup-cgroup.sh
+ExecStart=/home/pi/bin/bypass-proxy /home/pi/bin/clash -f /home/pi/.config/clash/config.yaml
+Restart=on-failure
 
 [Install]
 WantedBy=multi-user.target
```
</details>

Output: 
```bash
...
INFO[0000] Start initial compatible provider 🎞StreamingSE 
INFO[0000] RESTful API listening at: 0.0.0.0:9090       
INFO[0000] SOCKS proxy listening at: :7891              
WARN[0000] Failed to start Redir UDP Listener: operation not permitted 
ERRO[0000] Start TProxy server error: operation not permitted 
INFO[0000] Redir proxy listening at: :7892              
INFO[0000] Mixed(http+socks5) proxy listening at: :7890 
INFO[0000] DNS server listening at: 0.0.0.0:50053
...
```

### 建议?
1. 由于使用的是 raspbian, 默认用户文件夹是 `/Home/pi/`, 使用路径名检查 package 是否安装会报错, 如 `if [ ! -d "/usr/lib/udev/rules.d" ];then`. 不知如下怎样: 
    - [Linux How can I prove if udev installed? SuperUser](https://superuser.com/questions/471147/linux-how-can-i-prove-if-udev-installed)
    - [How to know if I am using systemd on Linux? SuperUser](https://superuser.com/questions/1017959/how-to-know-if-i-am-using-systemd-on-linux#:~:text=The%20correct%20solution%20is%20to,run%2Fsystemd%2Fsystem%20directory.&text=If%20%2Fsbin%2Finit%20doesn',1%20instead%20with%20ps%201%20.&text=This%20bash%20statement%20will%20either,and%20exit%20the%20running%20script)
2. uninstall 时 ipv4 转发恢复为 0

**Comment by Kr328** [comment]
1. `/srv/clash` 目录确实应当具有 x 权限
2. tproxy 监听属于特权操作 需要 ROOT 或者 CAP_NET_ADMIN
3. 绑定低于 1024 端口需要 ROOT 或者 CAP_NET_BING_SERVICE
4. 使用 PROCESS-NAME 需要 ROOT
5. 创建 tun 需要 ROOT 或者 CAP_NET_ADMIN
6. 如果使用 udevc 或者 /run/systemd 之类的检查是否运行某些服务 就无法得知 应当将脚本安装在哪里 还不如直接检查是否存在安装路径

基于以上 2-5 点考虑 脚本默认服务使用 root 运行 避免一些不必要的麻烦

PS. clash wiki 里的非官方文档 脚本来自本仓库

**Comment by senocids** [comment]
2,3,5 感觉可以解决
```bash
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_NET_ADMIN
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_ADMIN
```

但如果 4 只能用 root 的话....
...
<details>
  <summary>其实用 sudo, clash core 也会有些小问题</summary>

external controller 用 relative 路径错了..
```bash
$ /usr/bin/sudo /home/pi/bin/bypass-proxy /home/pi/bin/clash -f /home/pi/.config/clash/config.yaml
FATA[0000] Parse config error: external-ui: /root/.config/clash/yacd-gh-pages not exist
```
</details>

**Comment by senocids** [comment]
Tun 还有个问题不知道要开新 issue? 

```sh
$ journalctl -u clash
DateTime raspberrypi systemd[1]: Starting A rule based proxy tunnel...
DateTime raspberrypi systemd[1]: Started A rule based proxy tunnel.
DateTime raspberrypi bypass-proxy[3524]: /home/pi/bin/bypass-proxy: line 3: bypass-proxy-pid: command not found
DateTime raspberrypi bypass-proxy[3524]: time="time" level=info msg="Start initial compatible provider Fallback"
DateTime raspberrypi bypass-proxy[3524]: time="time" level=info msg="Start initial compatible provider Streaming"
...
```

**Comment by senocids** [comment]
> Tun 还有个问题不知道要开新 issue?
> 
> ```shell
> $ journalctl -u clash
> DateTime raspberrypi systemd[1]: Starting A rule based proxy tunnel...
> DateTime raspberrypi systemd[1]: Started A rule based proxy tunnel.
> DateTime raspberrypi bypass-proxy[3524]: /home/pi/bin/bypass-proxy: line 3: bypass-proxy-pid: command not found
> ...
> ...
> DateTime raspberrypi bypass-proxy[3524]: time="time" level=warning msg="[TUN] macOS auto set route error: set route not supported on current platform"
> ```
没事了 /home/pi/bin/bypass-proxy 路径写全就不报错了

**Comment by senocids** [comment]
#### warning 解决
Note: 不解决会报错 `all DNS requests failed, first error: gateway not found `

根据 非官方 [wiki](https://lancellc.gitbook.io/clash/start-clash/clash-tun-mode) 的[引用](https://comzyh.gitbook.io/clash/real-ip-tun-example)

> `device-url` 控制 Tun NIC 的相关参数。`dev://IfName` 控制操作系统中网卡的名称，Linux 下可以为任何长度不超过16的英文，MacOS 下则必须设置为 `dev://utun`，实际生成的 NIC 名可能是 utun0-utun9，由 MacOS 决定。

需将之前的 config 改成
```yaml
tun:
  enable: true
  stack: gvisor # or system
  # macOS-auto-route: true
  # macOS-auto-detect-interface: true
  device-url: dev://utun
  dns-listen: 0.0.0.0:50053
  dns-hijack:
    - tcp://8.8.8.8:53
    - 8.8.8.8:1053
```
